"""Initial migration

Revision ID: 56f21f59d33b
Revises: 
Create Date: 2025-07-22 18:49:43.820664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f21f59d33b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_decks_name'), 'decks', ['name'], unique=False)
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcards_next_review_at'), 'flashcards', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_flashcard_id'), 'reviews', ['flashcard_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_flashcard_id'), table_name='reviews')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_next_review_at'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_name'), table_name='decks')
    # ### end Alembic commands ###
